### ISSUE TITLE
No support for memory-only NUMA domains

### ISSUE THREAD

**Issue by jklinkenberg** [numap-library/numap#11]
Currently the code crashes when dealing with systems that also contain memory-only NUMA domains.

This code is really problematic
```c++
    nb_numa_nodes = numa_num_configured_nodes();
    int nb_cpus = numa_num_configured_cpus();
    for (node = 0; node < nb_numa_nodes; node++) {
      struct bitmask *mask = numa_allocate_cpumask();
      numa_node_to_cpus(node, mask);
      numa_node_to_cpu[node] = -1;
      for (cpu = 0; cpu < nb_cpus; cpu++) {
        if (*(mask->maskp) & (1 << cpu)) {
          numa_node_to_cpu[node] = cpu;
          break;
        }
      }
      numa_bitmask_free(mask);
      if (numa_node_to_cpu[node] == -1) {
        nb_numa_nodes = -1; // to be handled properly
      }
    }
```
Especially,, as `nb_numa_nodes` is changed inside the loop that is still using it. Futher, `nb_numa_nodes` is unsigned. Setting it to -1 will result in an unexpected behavior. 

Even if I solve this issue numap still does not work on e.g. the example

**Comment by trahay** [comment]
Hi,
I tried to fix the problem in branch memory-only (see commit 69b08187158bfbdaa7b60371a2c063b041b18c08), but since I don't have access to a machine with such configuration, I can't test it. Can you try this branch ?
François

**Comment by jklinkenberg** [comment]
Hi, thanks for the quick response and implementation :)

Currently, I try to get numap + dependencies running on an Ice Lake systems (CPU family: 6 and Model: 106) which is not yet in the listing (numap.c), but I added it manually:
```c
case CPU_MODEL(6, 106):
    snprintf(arch->name, 256, "Ice Lake micro arch");
    //snprintf(arch->sampling_read_event, 256, "MEM_TRANS_RETIRED:LOAD_LATENCY:ldlat=3"); << This does not exist
    snprintf(arch->sampling_read_event, 256, "MEM_TRANS_RETIRED:LOAD_LATENCY_GT_4");
    snprintf(arch->sampling_write_event, 256, "MEM_INST_RETIRED:ALL_STORES");
    break;
```
I actually have access to those systems with 
* 2 regular NUMA domains (CPUs + memory)
* 2 regular NUMA domains (CPUs + memory) + 2 memory-only NUMA domains

On a system with regular NUMA domains the example works although PEBS seems not to be able to detect where the access has been served from:
```bash
Starting memory read sampling
Memory read sampling results

head = 0 compared to max = 266240
Thread 0: 0        samples
Thread 0: 0        local cache 1                  -nan%
Thread 0: 0        local cache 2                  -nan%
Thread 0: 0        local cache 3                  -nan%
Thread 0: 0        local cache LFB                -nan%
Thread 0: 0        local memory                   -nan%
Thread 0: 0        remote cache or local memory   -nan%
Thread 0: 0        remote memory                  -nan%
Thread 0: 0        unknown l3 miss                -nan%

head = 0 compared to max = 266240
Thread 1: 0        samples
Thread 1: 0        local cache 1                  -nan%
Thread 1: 0        local cache 2                  -nan%
Thread 1: 0        local cache 3                  -nan%
Thread 1: 0        local cache LFB                -nan%
Thread 1: 0        local memory                   -nan%
Thread 1: 0        remote cache or local memory   -nan%
Thread 1: 0        remote memory                  -nan%
Thread 1: 0        unknown l3 miss                -nan%

Total sample number : 0

Starting memory write sampling
Memory write sampling results

head = 262104 compared to max = 266240
Thread 0: 6391     samples
Thread 0: 0        local cache 1                  0.000%
Thread 0: 0        local cache 2                  0.000%
Thread 0: 0        local cache 3                  0.000%
Thread 0: 0        local cache LFB                0.000%
Thread 0: 0        local memory                   0.000%
Thread 0: 0        remote cache or local memory   0.000%
Thread 0: 0        remote memory                  0.000%
Thread 0: 6391     unknown l3 miss                100.000%

head = 262104 compared to max = 266240
Thread 1: 6391     samples
Thread 1: 0        local cache 1                  0.000%
Thread 1: 0        local cache 2                  0.000%
Thread 1: 0        local cache 3                  0.000%
Thread 1: 0        local cache LFB                0.000%
Thread 1: 0        local memory                   0.000%
Thread 1: 0        remote cache or local memory   0.000%
Thread 1: 0        remote memory                  0.000%
Thread 1: 6391     unknown l3 miss                100.000%

Total sample number : 22782
```
Any idea on that?

Next, I will try your commit on a system with also memory-only NUMA nodes

Kind regards
Jannis

**Comment by jklinkenberg** [comment]
Update: Your commit on systems with memory-only NUMA nodes seems to work. Thank you.

Currently, I'm still struggling with perf not able to detect where the accesses have been served from. After some digging it seems that the `sample` struct, more specifically the `perf_mem_data_src` struct is not filled correctly on my Ice Lake system. Looking at the values for `mem_op`, `mem_lvl` and `mem_snoop` I see:
```bash
mem_op = PERF_MEM_OP_NA
mem_lvl  = PERF_MEM_LVL_NA
mem_snoop = PERF_MEM_SNOOP_NA
```
Any idea what went wrong? Did I use the wrong counters (see above)?

**Comment by jklinkenberg** [comment]
@trahay Just to inform you. I found the bug for the load events on Ice Lake. It was a bug or maybe more an unconsidered case in libpfm4 because some umasks like `LOAD_LATENCY_GT_4` have implicitly contain information about `ldlat` which was not covered. Apparently, the library then sets wrong perf config and config1 values.

I created a merge request for a workaround (https://sourceforge.net/p/perfmon2/libpfm4/merge-requests/19/)
With that change load instructions can distinguish where they are severed from again.
Store events however are still not working properly on Ice Lake. I filed an Intel support ticket for that.

Thanks again for the quick resonse and implementation.

**Comment by trahay** [comment]
Thanks ! I tried your merge request on my laptop (with a Core i7-1165G7), and pfm initialization fails :(
I didn't investigate much, but the `"LOAD_LATENCY_GT_X" ` seems to generate errors: if I replace it with `"LOAD_LATENCY"`, the initialization works.
