### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by nnewram** [numap-library/numap#15]
check is https://github.com/numap-library/numap/blob/5c120ef9411f4150293f5cfd600e3498153f97b2/examples/showevtinfo.c#L253

declaration is unsigned https://github.com/numap-library/numap/blob/5c120ef9411f4150293f5cfd600e3498153f97b2/examples/showevtinfo.c#L195

snprintf gives how many would have written here https://github.com/numap-library/numap/blob/5c120ef9411f4150293f5cfd600e3498153f97b2/examples/showevtinfo.c#L252

which then could write out of bounds. due to https://github.com/numap-library/numap/blob/5c120ef9411f4150293f5cfd600e3498153f97b2/examples/showevtinfo.c#L250

probably no impact, thought I'd make an issue wither way

**Comment by trahay** [comment]
Thanks for the bug report !
This should be fixed by commit #7b9529b.
