### ISSUE TITLE
Can't run example

### ISSUE THREAD

**Issue by cycyyy** [numap-library/numap#2]
I'm try to run the example on vmware with kernel version (Linux version 4.15.0-38-generic (buildd@lcy01-amd64-023) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018) and cpu (Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz)
 i get the exception: 
Starting memory read sampling -> numap_sampling_start error : perf_event ==> Operation not supported

Then I try to run the example on server with kernel version( Linux version 3.10.0-327.36.3.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) ) #1 SMP Mon Oct 24 16:09:20 UTC 2016) and cpu (Intel(R) Xeon Phi(TM) CPU 7210 @ 1.30GHz)
and i get the exception: 
Segmentation fault

**Comment by trahay** [comment]
It seems like the two CPUs you used are currently not supported by Numap, so you should have another error ("libnumap: architecture not supported"). Did you do any modification to numap ?

**Comment by cycyyy** [comment]
No. I haven'd done any modification to numap

**Comment by cycyyy** [comment]
Could you please send me the URL about ".sampling_read_event and .sampling_write_event can be found in the Intel Software Developpers Manuel (Chapter 19)". I can't find it .
