### ISSUE TITLE
Sample read and write event at same time.

### ISSUE THREAD

**Issue by cycyyy** [numap-library/numap#3]
Can i sample the read and write at same time?
I read the https://stackoverflow.com/questions/42088515/perf-event-open-how-to-monitoring-multiple-events and try to make a group between write_sample and read_sample, (like this `perf_event_open(&pe, measure->tids[thread], cpu, measure->fd_per_tid[thread], 0)` )but it shows that "error when calling perf_event_open: Invalid argument". So is there some way to sample read events and write events at same time?

**Comment by ManuelSelva** [comment]
Yes you can if your hardware support both the sampling of read and the 
sampling of write. You just have to make several calls to numap to start 
both the sampling of write and reads.

Compared to the stackoverflow link you mentionned, this is done inside 
numap by making two different calls to perf_event_open.

Hope this help,

--
Manu

**Comment by trahay** [comment]
Here's an example of how to do this (from [NumaMMA  source code](https://github.com/numamma/numamma/blob/master/src/mem_sampling.c) ) :
`
void mem_sampling_thread_init() {
  pid_t tid = syscall(SYS_gettid);
  int res = numap_sampling_init_measure(&sm, 1, sampling_rate, 32);
  if(res < 0) {
    abort();
  }
  numap_sampling_read_start(&sm);
  if(res < 0) {
    abort();
  }

  // Start write sampling
  res = numap_sampling_init_measure(&sm_wr, 1, sampling_rate, 32);
  if(res < 0) {
    abort();
  }
    res = numap_sampling_write_start(&sm_wr);
    if(res < 0) {
      abort();
    }
  }

}
`
